blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/orgs/NillionNetwork/discussions
    about: Ask questions about your own code on the Nillion Discussions tab.
