# This workflow builds and tests the project.
# It runs for every pull request.
# For testing currently uses the tests in nilvm repo.
name: Build

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.24"
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Format check
        run: make format-check
      - name: Lint with pylint
        run: |
          uv run pylint nada_dsl/
      - name: Test with pytest
        run: |
          uv run pytest
  # Test that the compiled programs are compatible the NilVm backend.
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: NillionNetwork/nilvm
          path: nilvm
          ref: main
      - name: Replace nilvms's nada_dsl with this version
        uses: actions/checkout@v4
        with:
          path: nilvm/nada-lang/nada_dsl
      - name: Check that test-programs compile
        run: |
          pip install -U virtualenv
          cd nilvm && cargo build -p test-programs
      - name: Run nada autotests
        run: |
          pip install nilvm/nada-lang/nada_dsl/nada_mir
          pip install nilvm/nada-lang/nada_dsl
          mkdir target
          cd nilvm 
          RUST_LOG=warn cargo run -p auto-tests
