# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nillion/nada/v1/types.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf


@dataclass(eq=False, repr=False)
class Array(betterproto.Message):
    """Array type, defines a collection of homogeneous values"""

    contained_type: "NadaType" = betterproto.message_field(1)
    """Type of the elements of this array"""

    size: int = betterproto.uint32_field(2)
    """Size of the array"""


@dataclass(eq=False, repr=False)
class Tuple(betterproto.Message):
    """Tuple type, a binary tuple"""

    left: "NadaType" = betterproto.message_field(1)
    """Left type"""

    right: "NadaType" = betterproto.message_field(2)
    """Right type"""


@dataclass(eq=False, repr=False)
class Ntuple(betterproto.Message):
    fields: List["NadaType"] = betterproto.message_field(1)
    """Number of elements in the tuple"""


@dataclass(eq=False, repr=False)
class ObjectEntry(betterproto.Message):
    name: str = betterproto.string_field(1)
    """Name of the field"""

    type: "NadaType" = betterproto.message_field(2)
    """Type of the field"""


@dataclass(eq=False, repr=False)
class Object(betterproto.Message):
    fields: List["ObjectEntry"] = betterproto.message_field(1)
    """
    Fields of the object, we use repeated ObjectEntry ordered by name to have deterministic compilation
    """


@dataclass(eq=False, repr=False)
class NadaType(betterproto.Message):
    integer: "betterproto_lib_google_protobuf.Empty" = betterproto.message_field(
        1, group="nada_type"
    )
    unsigned_integer: "betterproto_lib_google_protobuf.Empty" = (
        betterproto.message_field(2, group="nada_type")
    )
    boolean: "betterproto_lib_google_protobuf.Empty" = betterproto.message_field(
        3, group="nada_type"
    )
    secret_integer: "betterproto_lib_google_protobuf.Empty" = betterproto.message_field(
        4, group="nada_type"
    )
    secret_unsigned_integer: "betterproto_lib_google_protobuf.Empty" = (
        betterproto.message_field(5, group="nada_type")
    )
    secret_boolean: "betterproto_lib_google_protobuf.Empty" = betterproto.message_field(
        6, group="nada_type"
    )
    ecdsa_private_key: "betterproto_lib_google_protobuf.Empty" = (
        betterproto.message_field(7, group="nada_type")
    )
    ecdsa_digest_message: "betterproto_lib_google_protobuf.Empty" = (
        betterproto.message_field(8, group="nada_type")
    )
    ecdsa_signature: "betterproto_lib_google_protobuf.Empty" = (
        betterproto.message_field(9, group="nada_type")
    )
    array: "Array" = betterproto.message_field(10, group="nada_type")
    tuple: "Tuple" = betterproto.message_field(11, group="nada_type")
    ntuple: "Ntuple" = betterproto.message_field(12, group="nada_type")
    object: "Object" = betterproto.message_field(13, group="nada_type")
