# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nillion/nada/v1/types.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    Dict,
    List,
)

import betterproto


class ScalarType(betterproto.Enum):
    """
    The Scalar Type enumeration.enum
     List of the different scalar types in Nada.
    """

    INTEGER = 0
    UNSIGNED_INTEGER = 1
    BOOLEAN = 2
    SECRET_INTEGER = 3
    SECRET_UNSIGNED_INTEGER = 4
    SECRET_BOOLEAN = 5
    ECDSA_PRIVATE_KEY = 6
    """ECDSA private key for the threshold ecdsa signature feature."""

    ECDSA_DIGEST_MESSAGE = 7
    """Public ECDSA message digest."""

    ECDSA_SIGNATURE = 8
    """Public ECDSA signature."""


@dataclass(eq=False, repr=False)
class Array(betterproto.Message):
    """Array type, defines a collection of homogeneous values"""

    size: int = betterproto.uint32_field(1)
    """Size of the array"""


@dataclass(eq=False, repr=False)
class Tuple(betterproto.Message):
    """Tuple type, a binary tuple"""

    left: "NadaType" = betterproto.message_field(1)
    """Left type"""

    right: "NadaType" = betterproto.message_field(2)
    """Right type"""


@dataclass(eq=False, repr=False)
class CollectionType(betterproto.Message):
    """Collection type, defines a collection of same values"""

    array: "Array" = betterproto.message_field(1, group="collection_type")
    contained_type: "NadaType" = betterproto.message_field(2)
    """Type of the elements of this collection"""


@dataclass(eq=False, repr=False)
class Ntuple(betterproto.Message):
    fields: List["NadaType"] = betterproto.message_field(1)
    """Number of elements in the tuple"""


@dataclass(eq=False, repr=False)
class Object(betterproto.Message):
    fields: Dict[str, "NadaType"] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )
    """Number of elements in the object"""


@dataclass(eq=False, repr=False)
class NadaType(betterproto.Message):
    scalar: "ScalarType" = betterproto.enum_field(1, group="nada_type")
    tuple: "Tuple" = betterproto.message_field(2, group="nada_type")
    collection: "CollectionType" = betterproto.message_field(3, group="nada_type")
    ntuple: "Ntuple" = betterproto.message_field(4, group="nada_type")
    object: "Object" = betterproto.message_field(5, group="nada_type")
